# .github/workflows/deploy.yml

# name: K-ook Backend CI Pipeline

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:

# jobs:
#   build:
#     runs-on: ubuntu-latest # 테스트 환경 (Linux)
#     strategy:
#       matrix:
#         python-version: ["3.11"] # 사용할 파이썬 버전

#     steps:
#     - name: 1. 코드 체크아웃
#       uses: actions/checkout@v4

#     - name: 2. 파이썬 설치 (from matrix)
#       uses: actions/setup-python@v5
#       with:
#         python-version: ${{ matrix.python-version }}

#     - name: 3. 의존성(라이브러리) 설치
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#         # (테스트용 라이브러리가 있다면 여기에 추가)
#         pip install pytest httpx

#     - name: 4. 코드 스타일 검사 (Ruff)
#       run: |
#         pip install ruff
#         ruff check app
    
#     - name: 5. API 테스트 실행 (Pytest)
#       run: |
#         pytest

#     - name: 6. 배포 스크립트 실행
#     run: |
#         python -m uvicorn app.main:app --reload --port 8000